# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-21 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20200521_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(max_length=8000),
        ),
    ]
