# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20200522_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadvote',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thread_vote', to='forum.Thread'),
        ),
    ]
