# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-25 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_auto_20200524_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='postvote',
            name='thread',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Thread'),
        ),
    ]
