# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-25 14:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_postvote_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postvote',
            name='thread',
        ),
    ]
