# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-25 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_remove_postvote_thread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postvote',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='threadvote',
            options={'ordering': ['-date_created']},
        ),
    ]
