# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-29 13:15
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/default_img.jpg', null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
