# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200224_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/default_img.jpg', null=True, upload_to='profile_image'),
        ),
    ]
