# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-28 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200427_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='date_created',
        ),
    ]
