# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-07-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20200701_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donate_ticket_key', to='tickets.Ticket'),
        ),
    ]
