# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-28 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_donation_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
